# Generated by Django 2.1 on 2018-09-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(default='cse', max_length=10)),
                ('regulation', models.CharField(default='r16', max_length=10)),
                ('semester', models.CharField(default='1-1', max_length=10)),
                ('subname', models.CharField(max_length=10)),
                ('pdf', models.FileField(blank=True, upload_to='pdf')),
                ('unit', models.CharField(default=1, max_length=100)),
                ('teachername', models.CharField(default=None, max_length=100)),
                ('clgname', models.CharField(default=None, max_length=100)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='videourls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicName', models.CharField(max_length=100)),
                ('Topicpdf', models.FileField(blank=True, default='x', null=True, upload_to='pdf')),
                ('Topicurl', models.URLField(blank=True, null=True)),
                ('subname', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('clgname', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
